
/* Drop Triggers */

DROP TRIGGER TRI_NEW_TABLE_rptNo;
DROP TRIGGER TRI_TBL_BUSIN_businNo;
DROP TRIGGER TRI_TBL_BUSIN_BUSIN_NO;
DROP TRIGGER TRI_TBL_COUPON_COUPON_NUM;
DROP TRIGGER TRI_TBL_FEED_REPORT_rptNo;
DROP TRIGGER TRI_TBL_FEED_REPORT_RPT_NO;
DROP TRIGGER TRI_TBL_FEED_RP_REPORT_rptNo;
DROP TRIGGER TRI_TBL_FEED_RP_REPORT_RPT_NO;
DROP TRIGGER TRI_TBL_FREE_freeBno;
DROP TRIGGER TRI_TBL_FREE_FREE_BNO;
DROP TRIGGER TRI_TBL_FREE_REPORT_rptNo;
DROP TRIGGER TRI_TBL_GON_gonNo;
DROP TRIGGER TRI_TBL_GON_GON_BNO;
DROP TRIGGER TRI_TBL_MENU_menuNo;
DROP TRIGGER TRI_TBL_MENU_MENU_NO;
DROP TRIGGER TRI_TBL_MSG_msgNo;
DROP TRIGGER TRI_TBL_MSG_MSG_BNO;
DROP TRIGGER TRI_TBL_REPLY_freeRno;
DROP TRIGGER TRI_TBL_REPLY_FREE_RNO;
DROP TRIGGER TRI_TBL_REPORT_RPT_NO;
DROP TRIGGER TRI_TBL_RESERVATION_reservNo;
DROP TRIGGER TRI_TBL_RESERVATION_RESERV_NO;
DROP TRIGGER TRI_TBL_REVIEW_REPLY_REPORT_rptNo;
DROP TRIGGER TRI_TBL_REVIEW_REPLY_rvRno;
DROP TRIGGER TRI_TBL_REVIEW_REPLY_RV_RNO;
DROP TRIGGER TRI_TBL_REVIEW_REPORT_rptNo;
DROP TRIGGER TRI_TBL_REVIEW_rvNo;
DROP TRIGGER TRI_TBL_REVIEW_RV_NO;
DROP TRIGGER TRI_TBL_TIMEFEED_fdNo;
DROP TRIGGER TRI_TBL_TIMEFEED_FD_NO;



/* Drop Tables */

DROP TABLE TBL_BUSIN_ATTACH CASCADE CONSTRAINTS;
DROP TABLE TBL_BUSIN_FAVORITE CASCADE CONSTRAINTS;
DROP TABLE TBL_BUSIN_REPORT CASCADE CONSTRAINTS;
DROP TABLE TBL_COUPON CASCADE CONSTRAINTS;
DROP TABLE TBL_MENU_ATTACH CASCADE CONSTRAINTS;
DROP TABLE TBL_MENU CASCADE CONSTRAINTS;
DROP TABLE TBL_RESERVATION CASCADE CONSTRAINTS;
DROP TABLE TBL_REVIEW_ATTACH CASCADE CONSTRAINTS;
DROP TABLE TBL_REVIEW_REPLY_REPORT CASCADE CONSTRAINTS;
DROP TABLE TBL_REVIEW_REPLY CASCADE CONSTRAINTS;
DROP TABLE TBL_REVIEW_REPORT CASCADE CONSTRAINTS;
DROP TABLE TBL_REVIEW CASCADE CONSTRAINTS;
DROP TABLE TBL_BUSIN CASCADE CONSTRAINTS;
DROP TABLE TBL_FEED_REPORT CASCADE CONSTRAINTS;
DROP TABLE TBL_FEED_RP_REPORT CASCADE CONSTRAINTS;
DROP TABLE TBL_FOLLOWER CASCADE CONSTRAINTS;
DROP TABLE TBL_FOLLOWING CASCADE CONSTRAINTS;
DROP TABLE TBL_FREE_REPORT CASCADE CONSTRAINTS;
DROP TABLE TBL_FREE_REPLY_REPORT CASCADE CONSTRAINTS;
DROP TABLE TBL_REPLY CASCADE CONSTRAINTS;
DROP TABLE TBL_FREE CASCADE CONSTRAINTS;
DROP TABLE TBL_GON_ATTACH CASCADE CONSTRAINTS;
DROP TABLE TBL_GON CASCADE CONSTRAINTS;
DROP TABLE TBL_MSG_ATTACH CASCADE CONSTRAINTS;
DROP TABLE TBL_MSG CASCADE CONSTRAINTS;
DROP TABLE TBL_TIMEFEED_ATTACH CASCADE CONSTRAINTS;
DROP TABLE TBL_TIMEFEED_REPLY CASCADE CONSTRAINTS;
DROP TABLE TBL_TIMEFEED CASCADE CONSTRAINTS;
DROP TABLE TBL_USER_ATTACH CASCADE CONSTRAINTS;
DROP TABLE TBL_USER_AUTH CASCADE CONSTRAINTS;
DROP TABLE TBL_USERS CASCADE CONSTRAINTS;



/* Drop Sequences */

DROP SEQUENCE SEQ_NEW_TABLE_rptNo;
DROP SEQUENCE SEQ_TBL_BUSIN_businNo;
DROP SEQUENCE SEQ_TBL_BUSIN_BUSIN_NO;
DROP SEQUENCE SEQ_TBL_COUPON_COUPON_NUM;
DROP SEQUENCE SEQ_TBL_FEED_REPORT_rptNo;
DROP SEQUENCE SEQ_TBL_FEED_REPORT_RPT_NO;
DROP SEQUENCE SEQ_TBL_FEED_RP_REPORT_rptNo;
DROP SEQUENCE SEQ_TBL_FEED_RP_REPORT_RPT_NO;
DROP SEQUENCE SEQ_TBL_FREE_freeBno;
DROP SEQUENCE SEQ_TBL_FREE_FREE_BNO;
DROP SEQUENCE SEQ_TBL_FREE_REPORT_rptNo;
DROP SEQUENCE SEQ_TBL_GON_gonNo;
DROP SEQUENCE SEQ_TBL_GON_GON_BNO;
DROP SEQUENCE SEQ_TBL_MENU_menuNo;
DROP SEQUENCE SEQ_TBL_MENU_MENU_NO;
DROP SEQUENCE SEQ_TBL_MSG_msgNo;
DROP SEQUENCE SEQ_TBL_MSG_MSG_BNO;
DROP SEQUENCE SEQ_TBL_REPLY_freeRno;
DROP SEQUENCE SEQ_TBL_REPLY_FREE_RNO;
DROP SEQUENCE SEQ_TBL_REPORT_RPT_NO;
DROP SEQUENCE SEQ_TBL_RESERVATION_reservNo;
DROP SEQUENCE SEQ_TBL_RESERVATION_RESERV_NO;
DROP SEQUENCE SEQ_TBL_REVIEW_REPLY_REPORT_rptNo;
DROP SEQUENCE SEQ_TBL_REVIEW_REPLY_rvRno;
DROP SEQUENCE SEQ_TBL_REVIEW_REPLY_RV_RNO;
DROP SEQUENCE SEQ_TBL_REVIEW_REPORT_rptNo;
DROP SEQUENCE SEQ_TBL_REVIEW_rvNo;
DROP SEQUENCE SEQ_TBL_REVIEW_RV_NO;
DROP SEQUENCE SEQ_TBL_TIMEFEED_fdNo;
DROP SEQUENCE SEQ_TBL_TIMEFEED_FD_NO;




/* Create Sequences */

CREATE SEQUENCE SEQ_NEW_TABLE_rptNo INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TBL_BUSIN_businNo INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TBL_BUSIN_BUSIN_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TBL_COUPON_COUPON_NUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TBL_FEED_REPORT_rptNo INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TBL_FEED_REPORT_RPT_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TBL_FEED_RP_REPORT_rptNo INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TBL_FEED_RP_REPORT_RPT_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TBL_FREE_freeBno INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TBL_FREE_FREE_BNO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TBL_FREE_REPORT_rptNo INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TBL_GON_gonNo INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TBL_GON_GON_BNO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TBL_MENU_menuNo INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TBL_MENU_MENU_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TBL_MSG_msgNo INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TBL_MSG_MSG_BNO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TBL_REPLY_freeRno INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TBL_REPLY_FREE_RNO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TBL_REPORT_RPT_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TBL_RESERVATION_reservNo INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TBL_RESERVATION_RESERV_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TBL_REVIEW_REPLY_REPORT_rptNo INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TBL_REVIEW_REPLY_rvRno INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TBL_REVIEW_REPLY_RV_RNO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TBL_REVIEW_REPORT_rptNo INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TBL_REVIEW_rvNo INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TBL_REVIEW_RV_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TBL_TIMEFEED_fdNo INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TBL_TIMEFEED_FD_NO INCREMENT BY 1 START WITH 1;



/* Create Tables */

-- 점포 테이블
CREATE TABLE TBL_BUSIN
(
	-- 아이디
	userId varchar2(12) NOT NULL,
	-- 점포번호 : SEQ_BUSIN를 이용
	businNo number(10) NOT NULL,
	-- 사업자등록번호
	lisenceNo number(10) NOT NULL,
	-- 점포명
	businNm varchar2(40) NOT NULL,
	-- 점포주소1
	businAddr varchar2(50) DEFAULT '"서울시"' NOT NULL,
	-- 점포주소2
	businAddr2 varchar2(50) NOT NULL,
	-- 점포주소3
	businAddr3 varchar2(50) NOT NULL,
	-- 점포 전화번호
	businTel number(12) NOT NULL,
	-- 휴무일
	businClosedDay varchar2(10) NOT NULL,
	-- 요리종목
	businFood varchar2(10) NOT NULL,
	-- 수용가능인원수
	businScale number(12) NOT NULL,
	-- 영업시간1
	businOpen varchar2(10) DEFAULT '"00:00"' NOT NULL,
	-- 영업시간2
	businClosed varchar2(10) DEFAULT '"24:00"' NOT NULL,
	-- 주차장유무
	businPark varchar2(10) DEFAULT '"무"' NOT NULL,
	-- 사업자등록증사진
	businBusPhoto varchar2(50) NOT NULL,
	-- 대표사진
	businPhoto varchar2(50),
	-- 기타사항
	businEtc varchar2(50),
	PRIMARY KEY (businNo)
);


-- 점포 첨부파일 테이블
CREATE TABLE TBL_BUSIN_ATTACH
(
	-- 식별자
	uuId varchar2(100) NOT NULL,
	-- 점포번호 : SEQ_BUSIN를 이용
	businNo number(10) NOT NULL,
	-- 파일명
	fileName varchar2(100) NOT NULL,
	-- 파일경로
	businPath varchar2(100) NOT NULL,
	-- 파일타입
	fileType char(1) NOT NULL,
	PRIMARY KEY (uuId)
);


-- 점포 즐겨찾기 테이블
CREATE TABLE TBL_BUSIN_FAVORITE
(
	-- 아이디
	userId varchar2(12) NOT NULL,
	-- 점포번호 : SEQ_BUSIN를 이용
	businNo number(10) NOT NULL
);


-- 점포 신고 테이블
CREATE TABLE TBL_BUSIN_REPORT
(
	-- 신고번호
	reportNo number(10,0) NOT NULL,
	-- 점포번호 : SEQ_BUSIN를 이용
	businNo number(10) NOT NULL,
	-- 신고자
	reporter varchar2(12) NOT NULL,
	-- 신고내용
	reportCon varchar2(200),
	-- 신고일시
	reportDate varchar2(12),
	-- 신고처리
	processReport varchar2(12),
	-- 제재내용
	restrictionContent varchar2(12),
	-- 제재사유
	restrictionReason varchar2(12),
	-- 제재일시
	restrictionDate varchar2(12),
	PRIMARY KEY (reportNo)
);


-- 쿠폰 테이블
CREATE TABLE TBL_COUPON
(
	-- 쿠폰번호 : SEQ_COUPON를 이용
	couponNo number NOT NULL,
	-- 점포번호 : SEQ_BUSIN를 이용
	businNo number(10) NOT NULL,
	-- 쿠폰제목
	couponName varchar2(20) NOT NULL,
	-- 쿠폰 내용
	couponContent varchar2(100) NOT NULL,
	PRIMARY KEY (couponNo)
);


-- 피드 신고
CREATE TABLE TBL_FEED_REPORT
(
	-- 신고 번호
	rptNo number(12) NOT NULL,
	-- 피드 번호
	fdNo number(12) NOT NULL,
	-- 신고자
	reporter varchar2(12) NOT NULL,
	-- 신고일시
	rptDate date NOT NULL,
	-- 신고 내용
	rptContent varchar2(200) NOT NULL,
	-- 신고처리
	processReport varchar2(12),
	-- 제재내용
	restrictionContent varchar2(12),
	-- 제재사유
	restrictionReason varchar2(12),
	-- 제재일시
	restrictionDate varchar2(12),
	PRIMARY KEY (rptNo)
);


-- 피드 댓글 신고
CREATE TABLE TBL_FEED_RP_REPORT
(
	-- 신고 번호
	rptNo number(12) NOT NULL,
	-- 피드 댓글 번호
	fdRpNo number(12) NOT NULL,
	-- 신고자
	reporter varchar2(12) NOT NULL,
	-- 신고 내용
	rptContent varchar2(200) NOT NULL,
	-- 신고일시
	rptDate date NOT NULL,
	-- 신고처리
	processReport varchar2(12),
	-- 제재내용
	restrictionContent varchar2(12),
	-- 제재사유
	restrictionReason varchar2(12),
	-- 제재일시
	restrictionDate varchar2(12),
	PRIMARY KEY (rptNo)
);


-- 팔로워 목록
CREATE TABLE TBL_FOLLOWER
(
	-- 아이디
	userId varchar2(12) NOT NULL,
	-- 팔로워 닉네임
	followerUser varchar2(12) NOT NULL
);


-- 팔로잉 목록
CREATE TABLE TBL_FOLLOWING
(
	-- 아이디
	userId varchar2(12) NOT NULL,
	-- 팔로잉 닉네임
	followingUser varchar2(12) NOT NULL
);


-- 자유게시판 테이블
CREATE TABLE TBL_FREE
(
	-- 게시판번호 : SEQ_FREE이용
	freeBno number NOT NULL,
	-- 작성자
	writer varchar2(12) NOT NULL,
	-- 제목
	title varchar2(30),
	-- 내용
	content varchar2(200) NOT NULL,
	-- 작성일자
	regDate date,
	-- 수정일자 : 
	-- 
	-- 
	updateDate date,
	-- 댓글 수
	replyCnt number(5,0) DEFAULT 0,
	PRIMARY KEY (freeBno)
);


-- 게시글 댓글 신고 테이블
CREATE TABLE TBL_FREE_REPLY_REPORT
(
	-- 신고 번호 : SEQ_FREE_REPLY_RPT를 이용
	rptNo number(12) NOT NULL,
	-- 댓글 번호 : SEQ_REPLY를 이용
	freeRno number NOT NULL,
	-- 신고자
	reporter varchar2(12) NOT NULL,
	-- 신고일시
	rptDate date NOT NULL,
	-- 신고 내용
	rptContent varchar2(200) NOT NULL,
	-- 제재내용
	restrictionContent varchar2(12),
	-- 제재사유
	restrictionReason varchar2(12),
	-- 제재일시
	restrictionDate varchar2(12),
	PRIMARY KEY (rptNo)
);


-- 게시글 신고 테이블
CREATE TABLE TBL_FREE_REPORT
(
	-- 신고 번호 : SEQ_REVIEW_REPLY_RPT를 이용
	rptNo number(12) NOT NULL,
	-- 게시판번호 : SEQ_FREE이용
	freeBno number NOT NULL,
	-- 신고자
	reporter varchar2(12) NOT NULL,
	-- 신고일시
	rptDate date,
	-- 신고 내용
	rptContent varchar2(200),
	-- 신고처리
	processReport varchar2(12),
	-- 제재내용
	restrictionContent varchar2(12),
	-- 제재사유
	restrictionReason varchar2(12),
	-- 제재일시
	restrictionDate varchar2(12),
	PRIMARY KEY (rptNo)
);


-- 공지사항 테이블
CREATE TABLE TBL_GON
(
	-- 공지게시판 번호 : SEQ_GON이용
	gonNo number(10) NOT NULL,
	-- 공지 제목
	gonName varchar2(100),
	-- 공지 내용
	gonContent varchar2(500) NOT NULL,
	-- 공지 작성일자
	gonRegdate date DEFAULT SYSDATE,
	-- 공지 수정일자
	gonUpdatedate date DEFAULT SYSDATE,
	PRIMARY KEY (gonNo)
);


-- 공지 첨부파일 테이블
CREATE TABLE TBL_GON_ATTACH
(
	-- 식별자
	gonUuid varchar2(100) NOT NULL,
	-- 공지게시판 번호 : SEQ_GON이용
	gonNo number(10) NOT NULL,
	-- 파일이름
	gonFilename varchar2(100) NOT NULL,
	-- 경로
	gonUploadPath varchar2(200) NOT NULL,
	-- 파일타입
	gonFileType char DEFAULT 'I',
	PRIMARY KEY (gonUuid)
);


-- 메뉴 테이블
CREATE TABLE TBL_MENU
(
	-- 메뉴번호 : SEQ_MENU를 이용
	menuNo number(10,0) NOT NULL,
	-- 점포번호 : SEQ_BUSIN를 이용
	businNo number(10) NOT NULL,
	-- 메뉴이름
	menuNm varchar2(30) NOT NULL,
	-- 메뉴가격
	menuPrice number NOT NULL,
	PRIMARY KEY (menuNo)
);


-- 메뉴 파일 테이블
CREATE TABLE TBL_MENU_ATTACH
(
	-- 식별자
	uuid varchar2(100) NOT NULL,
	-- 메뉴번호 : SEQ_MENU를 이용
	menuNo number(10,0) NOT NULL,
	-- 파일명
	fileName varchar2(100) NOT NULL,
	-- 파일경로
	menuPath varchar2(100) NOT NULL,
	PRIMARY KEY (uuid)
);


-- 쪽지함 테이블
CREATE TABLE TBL_MSG
(
	-- 쪽지 번호 : SEQ_MSG이용
	msgNo number(10) NOT NULL,
	-- 쪽지작성자
	msgSender varchar2(12) NOT NULL,
	-- 쪽지수신자
	msgRecever varchar2(12) NOT NULL,
	-- 쪽지 내용
	msgContent varchar2(500) NOT NULL,
	-- 작성일자
	msgRegdate date,
	-- 읽음표시
	msgCheck number DEFAULT 1 NOT NULL,
	PRIMARY KEY (msgNo)
);


-- 쪽지 첨부파일 테이블
CREATE TABLE TBL_MSG_ATTACH
(
	-- 식별자
	gonUuid varchar2(100) NOT NULL,
	-- 쪽지 번호 : SEQ_MSG이용
	msgNo number(10) NOT NULL,
	-- 경로
	gonUploadPath varchar2(200) NOT NULL,
	-- 파일이름
	gonFilename varchar2(100) NOT NULL,
	-- 파일타입
	gonFileType char DEFAULT 'I',
	PRIMARY KEY (gonUuid)
);


-- 댓글 테이블
CREATE TABLE TBL_REPLY
(
	-- 댓글 번호 : SEQ_REPLY를 이용
	freeRno number NOT NULL,
	-- 게시판번호 : SEQ_FREE이용
	freeBno number NOT NULL,
	-- 댓글작성자
	rplWriter varchar2(12) NOT NULL,
	-- 댓글 내용
	reply varchar2(200) NOT NULL,
	-- 작성일자
	replyDate date DEFAULT SYSDATE,
	-- 수정일자
	updateDate date DEFAULT SYSDATE,
	PRIMARY KEY (freeRno)
);


-- 예약 테이블
CREATE TABLE TBL_RESERVATION
(
	-- 예약 번호 : SEQ_RESERV를 이용
	reservNo number NOT NULL,
	-- 점포번호 : SEQ_BUSIN를 이용
	businNo number(10) NOT NULL,
	-- 예약자
	reserver varchar2(12) NOT NULL,
	-- 예약날짜
	reservDate date NOT NULL,
	-- 인원수
	headCount number(3,0) DEFAULT 1 NOT NULL,
	-- 기타사항
	request varchar2(100),
	-- 총 가격
	totalPrice number NOT NULL,
	-- 결제일자
	payDate date,
	-- 결제 번호
	orderNum varchar2(30),
	PRIMARY KEY (reservNo)
);


-- 점포리뷰 테이블
CREATE TABLE TBL_REVIEW
(
	-- 리뷰번호 : SEQ_RV_NO를 이용
	rvNo number(12) NOT NULL,
	-- 점포번호 : SEQ_BUSIN를 이용
	businNo number(10) NOT NULL,
	-- 리뷰작성자
	rvWriter varchar2(12) NOT NULL,
	-- 리뷰제목
	rvTitle varchar2(40) NOT NULL,
	-- 별점
	stars number(1) DEFAULT 5,
	-- 리뷰내용
	rvContent varchar2(2000) NOT NULL,
	-- 작성일자
	regDate date DEFAULT SYSDATE,
	-- 수정일자
	updateDate date DEFAULT SYSDATE,
	-- 댓글 수
	replyCnt number(5,0) DEFAULT 0,
	PRIMARY KEY (rvNo)
);


-- 리뷰첨부파일 테이블
CREATE TABLE TBL_REVIEW_ATTACH
(
	-- 식별자
	uuId varchar2(100) NOT NULL,
	-- 리뷰번호 : SEQ_RV_NO를 이용
	rvNo number(12) NOT NULL,
	-- 파일명
	rvFilename varchar2(100) NOT NULL,
	-- 파일위치
	uploadPath varchar2(100) NOT NULL,
	PRIMARY KEY (uuId)
);


-- 리뷰댓글 테이블
CREATE TABLE TBL_REVIEW_REPLY
(
	-- 리뷰댓글번호
	rvRno number(12) NOT NULL,
	-- 리뷰번호 : SEQ_RV_NO를 이용
	rvNo number(12) NOT NULL,
	-- 리뷰댓글작성자
	rvRWritwr varchar2(12) NOT NULL,
	-- 리뷰댓글내용
	rvReply varchar2(1000),
	-- 작성일자
	regDate date DEFAULT SYSDATE,
	-- 수정일자
	updateDate date DEFAULT SYSDATE,
	PRIMARY KEY (rvRno)
);


-- 리뷰 댓글 신고 테이블
CREATE TABLE TBL_REVIEW_REPLY_REPORT
(
	-- 신고 번호 : SEQ_REVIEW_REPLY_RPT를 이용
	rptNo number(12) NOT NULL,
	-- 리뷰댓글번호
	rvRno number(12) NOT NULL,
	-- 신고자
	reporter varchar2(12) NOT NULL,
	-- 신고일시
	rptDate date,
	-- 신고 내용
	rptContent varchar2(200),
	-- 신고처리
	processReport varchar2(12),
	-- 제재내용
	restrictionContent varchar2(12),
	-- 제재사유
	restrictionReason varchar2(12),
	-- 제재일시
	restrictionDate varchar2(12),
	PRIMARY KEY (rptNo)
);


-- 리뷰 신고 테이블
CREATE TABLE TBL_REVIEW_REPORT
(
	-- 신고 번호 : SEQ_REVIEW_RPT를 이용
	rptNo number(12) NOT NULL,
	-- 리뷰번호 : SEQ_RV_NO를 이용
	rvNo number(12) NOT NULL,
	-- 신고자
	reporter varchar2(12) NOT NULL,
	-- 신고일시
	rptDate date DEFAULT SYSDATE NOT NULL,
	-- 신고 내용
	rptContent varchar2(200) NOT NULL,
	-- 신고처리
	processReport varchar2(12),
	-- 제재내용
	restrictionContent varchar2(12),
	-- 제재사유
	restrictionReason varchar2(12),
	-- 제재일시
	restrictionDate varchar2(12),
	PRIMARY KEY (rptNo)
);


-- 타임라인 피드
CREATE TABLE TBL_TIMEFEED
(
	-- 피드 번호
	fdNo number(12) NOT NULL,
	-- 피드 내용
	fdContent varchar2(500) NOT NULL,
	-- 작성자
	writer varchar2(12) NOT NULL,
	-- 등록일
	regDate date NOT NULL,
	-- 수정일
	updateDate date NOT NULL,
	-- 좋아요
	likeCount number(5),
	-- 댓글 수
	replyCnt number(5,0),
	PRIMARY KEY (fdNo)
);


-- 피드 첨부파일
CREATE TABLE TBL_TIMEFEED_ATTACH
(
	-- 피드 번호
	fdNo number(12) NOT NULL,
	-- 식별자
	uuid varchar2(100) NOT NULL,
	-- 파일 경로
	uploadPath varchar2(200) NOT NULL,
	-- 파일명
	fileName varchar2(100) NOT NULL,
	-- 파일 유형
	fileType char(1) NOT NULL,
	PRIMARY KEY (uuid)
);


-- 타임라인 피드 댓글
CREATE TABLE TBL_TIMEFEED_REPLY
(
	-- 피드 댓글 번호
	fdRpNo number(12) NOT NULL,
	-- 피드 번호
	fdNo number(12) NOT NULL,
	-- 댓글작성자
	rplWriter varchar2(12) NOT NULL,
	-- 댓글 내용
	fdRpContent varchar2(200) NOT NULL,
	-- 등록일
	regDate date NOT NULL,
	-- 수정일
	updateDate date NOT NULL,
	PRIMARY KEY (fdRpNo)
);


-- 회원 테이블
CREATE TABLE TBL_USERS
(
	-- 아이디
	userId varchar2(12) NOT NULL,
	-- 이름
	userNm varchar2(12) NOT NULL,
	-- 비밀번호
	userPw varchar2(12) NOT NULL,
	-- 닉네임
	nick varchar2(12) NOT NULL UNIQUE,
	-- 생년월일
	birthDate number(10) NOT NULL,
	-- 성별
	sex char(4) NOT NULL,
	-- 이메일
	email varchar2(80) NOT NULL UNIQUE,
	-- 전화번호
	phoneNo varchar2(20) NOT NULL,
	-- 주소1
	addr1 varchar2(50) DEFAULT '서울시' NOT NULL,
	-- 주소2
	addr2 varchar2(50) NOT NULL,
	-- 주소3
	addr3 varchar2(50) NOT NULL,
	-- 등록일
	regDate date NOT NULL,
	-- 회원등급
	grade varchar2(20) NOT NULL,
	-- 포인트
	userPoint number(10) NOT NULL,
	-- 권한
	auth varchar2(12) NOT NULL,
	-- 선호요리
	fvrFood varchar2(30),
	-- 선호가게
	fvrRes varchar2(30),
	-- 자기소개
	pfContent varchar2(70),
	PRIMARY KEY (userId)
);


-- 회원 첨부파일 테이블
CREATE TABLE TBL_USER_ATTACH
(
	-- 식별자
	uuId varchar2(100) NOT NULL,
	-- 아이디
	userId varchar2(12) NOT NULL,
	-- 파일명
	fileName varchar2(100) NOT NULL,
	-- 파일위치
	uploadPath varchar2(100) NOT NULL,
	PRIMARY KEY (uuId)
);


-- 유저인증테이블
CREATE TABLE TBL_USER_AUTH
(
	-- 유저id
	userid varchar2(12) NOT NULL,
	-- 권한
	auth varchar2(50) NOT NULL
);



/* Create Foreign Keys */

ALTER TABLE TBL_BUSIN_ATTACH
	ADD FOREIGN KEY (businNo)
	REFERENCES TBL_BUSIN (businNo)
;


ALTER TABLE TBL_BUSIN_FAVORITE
	ADD FOREIGN KEY (businNo)
	REFERENCES TBL_BUSIN (businNo)
;


ALTER TABLE TBL_BUSIN_REPORT
	ADD FOREIGN KEY (businNo)
	REFERENCES TBL_BUSIN (businNo)
;


ALTER TABLE TBL_COUPON
	ADD FOREIGN KEY (businNo)
	REFERENCES TBL_BUSIN (businNo)
;


ALTER TABLE TBL_MENU
	ADD FOREIGN KEY (businNo)
	REFERENCES TBL_BUSIN (businNo)
;


ALTER TABLE TBL_RESERVATION
	ADD FOREIGN KEY (businNo)
	REFERENCES TBL_BUSIN (businNo)
;


ALTER TABLE TBL_REVIEW
	ADD FOREIGN KEY (businNo)
	REFERENCES TBL_BUSIN (businNo)
;


ALTER TABLE TBL_FREE_REPORT
	ADD FOREIGN KEY (freeBno)
	REFERENCES TBL_FREE (freeBno)
;


ALTER TABLE TBL_REPLY
	ADD FOREIGN KEY (freeBno)
	REFERENCES TBL_FREE (freeBno)
;


ALTER TABLE TBL_GON_ATTACH
	ADD FOREIGN KEY (gonNo)
	REFERENCES TBL_GON (gonNo)
;


ALTER TABLE TBL_MENU_ATTACH
	ADD FOREIGN KEY (menuNo)
	REFERENCES TBL_MENU (menuNo)
;


ALTER TABLE TBL_MSG_ATTACH
	ADD FOREIGN KEY (msgNo)
	REFERENCES TBL_MSG (msgNo)
;


ALTER TABLE TBL_FREE_REPLY_REPORT
	ADD FOREIGN KEY (freeRno)
	REFERENCES TBL_REPLY (freeRno)
;


ALTER TABLE TBL_REVIEW_ATTACH
	ADD FOREIGN KEY (rvNo)
	REFERENCES TBL_REVIEW (rvNo)
;


ALTER TABLE TBL_REVIEW_REPLY
	ADD FOREIGN KEY (rvNo)
	REFERENCES TBL_REVIEW (rvNo)
;


ALTER TABLE TBL_REVIEW_REPORT
	ADD FOREIGN KEY (rvNo)
	REFERENCES TBL_REVIEW (rvNo)
;


ALTER TABLE TBL_REVIEW_REPLY_REPORT
	ADD FOREIGN KEY (rvRno)
	REFERENCES TBL_REVIEW_REPLY (rvRno)
;


ALTER TABLE TBL_FEED_REPORT
	ADD FOREIGN KEY (fdNo)
	REFERENCES TBL_TIMEFEED (fdNo)
;


ALTER TABLE TBL_TIMEFEED_ATTACH
	ADD FOREIGN KEY (fdNo)
	REFERENCES TBL_TIMEFEED (fdNo)
;


ALTER TABLE TBL_TIMEFEED_REPLY
	ADD FOREIGN KEY (fdNo)
	REFERENCES TBL_TIMEFEED (fdNo)
;


ALTER TABLE TBL_FEED_RP_REPORT
	ADD FOREIGN KEY (fdRpNo)
	REFERENCES TBL_TIMEFEED_REPLY (fdRpNo)
;


ALTER TABLE TBL_BUSIN
	ADD FOREIGN KEY (userId)
	REFERENCES TBL_USERS (userId)
;


ALTER TABLE TBL_BUSIN_FAVORITE
	ADD FOREIGN KEY (userId)
	REFERENCES TBL_USERS (userId)
;


ALTER TABLE TBL_BUSIN_REPORT
	ADD FOREIGN KEY (reporter)
	REFERENCES TBL_USERS (userId)
;


ALTER TABLE TBL_FEED_REPORT
	ADD FOREIGN KEY (reporter)
	REFERENCES TBL_USERS (userId)
;


ALTER TABLE TBL_FEED_RP_REPORT
	ADD FOREIGN KEY (reporter)
	REFERENCES TBL_USERS (userId)
;


ALTER TABLE TBL_FOLLOWER
	ADD FOREIGN KEY (followerUser)
	REFERENCES TBL_USERS (nick)
;


ALTER TABLE TBL_FOLLOWER
	ADD FOREIGN KEY (userId)
	REFERENCES TBL_USERS (userId)
;


ALTER TABLE TBL_FOLLOWING
	ADD FOREIGN KEY (userId)
	REFERENCES TBL_USERS (userId)
;


ALTER TABLE TBL_FOLLOWING
	ADD FOREIGN KEY (followingUser)
	REFERENCES TBL_USERS (nick)
;


ALTER TABLE TBL_FREE
	ADD FOREIGN KEY (writer)
	REFERENCES TBL_USERS (userId)
;


ALTER TABLE TBL_FREE_REPLY_REPORT
	ADD FOREIGN KEY (reporter)
	REFERENCES TBL_USERS (userId)
;


ALTER TABLE TBL_FREE_REPORT
	ADD FOREIGN KEY (reporter)
	REFERENCES TBL_USERS (userId)
;


ALTER TABLE TBL_MSG
	ADD FOREIGN KEY (msgRecever)
	REFERENCES TBL_USERS (userId)
;


ALTER TABLE TBL_MSG
	ADD FOREIGN KEY (msgSender)
	REFERENCES TBL_USERS (userId)
;


ALTER TABLE TBL_REPLY
	ADD FOREIGN KEY (rplWriter)
	REFERENCES TBL_USERS (userId)
;


ALTER TABLE TBL_RESERVATION
	ADD FOREIGN KEY (reserver)
	REFERENCES TBL_USERS (userId)
;


ALTER TABLE TBL_REVIEW
	ADD FOREIGN KEY (rvWriter)
	REFERENCES TBL_USERS (userId)
;


ALTER TABLE TBL_REVIEW_REPLY
	ADD FOREIGN KEY (rvRWritwr)
	REFERENCES TBL_USERS (userId)
;


ALTER TABLE TBL_REVIEW_REPLY_REPORT
	ADD FOREIGN KEY (reporter)
	REFERENCES TBL_USERS (userId)
;


ALTER TABLE TBL_REVIEW_REPORT
	ADD FOREIGN KEY (reporter)
	REFERENCES TBL_USERS (userId)
;


ALTER TABLE TBL_TIMEFEED
	ADD FOREIGN KEY (writer)
	REFERENCES TBL_USERS (userId)
;


ALTER TABLE TBL_TIMEFEED_REPLY
	ADD FOREIGN KEY (rplWriter)
	REFERENCES TBL_USERS (userId)
;


ALTER TABLE TBL_USER_ATTACH
	ADD FOREIGN KEY (userId)
	REFERENCES TBL_USERS (userId)
;


ALTER TABLE TBL_USER_AUTH
	ADD FOREIGN KEY (userid)
	REFERENCES TBL_USERS (userId)
;



/* Create Triggers */

CREATE OR REPLACE TRIGGER TRI_NEW_TABLE_rptNo BEFORE INSERT ON NEW_TABLE
FOR EACH ROW
BEGIN
	SELECT SEQ_NEW_TABLE_rptNo.nextval
	INTO :new.rptNo
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_TBL_BUSIN_businNo BEFORE INSERT ON TBL_BUSIN
FOR EACH ROW
BEGIN
	SELECT SEQ_TBL_BUSIN_businNo.nextval
	INTO :new.businNo
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_TBL_BUSIN_BUSIN_NO BEFORE INSERT ON TBL_BUSIN
FOR EACH ROW
BEGIN
	SELECT SEQ_TBL_BUSIN_BUSIN_NO.nextval
	INTO :new.BUSIN_NO
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_TBL_COUPON_COUPON_NUM BEFORE INSERT ON TBL_COUPON
FOR EACH ROW
BEGIN
	SELECT SEQ_TBL_COUPON_COUPON_NUM.nextval
	INTO :new.COUPON_NUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_TBL_FEED_REPORT_rptNo BEFORE INSERT ON TBL_FEED_REPORT
FOR EACH ROW
BEGIN
	SELECT SEQ_TBL_FEED_REPORT_rptNo.nextval
	INTO :new.rptNo
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_TBL_FEED_REPORT_RPT_NO BEFORE INSERT ON TBL_FEED_REPORT
FOR EACH ROW
BEGIN
	SELECT SEQ_TBL_FEED_REPORT_RPT_NO.nextval
	INTO :new.RPT_NO
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_TBL_FEED_RP_REPORT_rptNo BEFORE INSERT ON TBL_FEED_RP_REPORT
FOR EACH ROW
BEGIN
	SELECT SEQ_TBL_FEED_RP_REPORT_rptNo.nextval
	INTO :new.rptNo
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_TBL_FEED_RP_REPORT_RPT_NO BEFORE INSERT ON TBL_FEED_RP_REPORT
FOR EACH ROW
BEGIN
	SELECT SEQ_TBL_FEED_RP_REPORT_RPT_NO.nextval
	INTO :new.RPT_NO
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_TBL_FREE_freeBno BEFORE INSERT ON TBL_FREE
FOR EACH ROW
BEGIN
	SELECT SEQ_TBL_FREE_freeBno.nextval
	INTO :new.freeBno
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_TBL_FREE_FREE_BNO BEFORE INSERT ON TBL_FREE
FOR EACH ROW
BEGIN
	SELECT SEQ_TBL_FREE_FREE_BNO.nextval
	INTO :new.FREE_BNO
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_TBL_FREE_REPORT_rptNo BEFORE INSERT ON TBL_FREE_REPORT
FOR EACH ROW
BEGIN
	SELECT SEQ_TBL_FREE_REPORT_rptNo.nextval
	INTO :new.rptNo
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_TBL_GON_gonNo BEFORE INSERT ON TBL_GON
FOR EACH ROW
BEGIN
	SELECT SEQ_TBL_GON_gonNo.nextval
	INTO :new.gonNo
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_TBL_GON_GON_BNO BEFORE INSERT ON TBL_GON
FOR EACH ROW
BEGIN
	SELECT SEQ_TBL_GON_GON_BNO.nextval
	INTO :new.GON_BNO
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_TBL_MENU_menuNo BEFORE INSERT ON TBL_MENU
FOR EACH ROW
BEGIN
	SELECT SEQ_TBL_MENU_menuNo.nextval
	INTO :new.menuNo
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_TBL_MENU_MENU_NO BEFORE INSERT ON TBL_MENU
FOR EACH ROW
BEGIN
	SELECT SEQ_TBL_MENU_MENU_NO.nextval
	INTO :new.MENU_NO
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_TBL_MSG_msgNo BEFORE INSERT ON TBL_MSG
FOR EACH ROW
BEGIN
	SELECT SEQ_TBL_MSG_msgNo.nextval
	INTO :new.msgNo
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_TBL_MSG_MSG_BNO BEFORE INSERT ON TBL_MSG
FOR EACH ROW
BEGIN
	SELECT SEQ_TBL_MSG_MSG_BNO.nextval
	INTO :new.MSG_BNO
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_TBL_REPLY_freeRno BEFORE INSERT ON TBL_REPLY
FOR EACH ROW
BEGIN
	SELECT SEQ_TBL_REPLY_freeRno.nextval
	INTO :new.freeRno
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_TBL_REPLY_FREE_RNO BEFORE INSERT ON TBL_REPLY
FOR EACH ROW
BEGIN
	SELECT SEQ_TBL_REPLY_FREE_RNO.nextval
	INTO :new.FREE_RNO
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_TBL_REPORT_RPT_NO BEFORE INSERT ON TBL_REPORT
FOR EACH ROW
BEGIN
	SELECT SEQ_TBL_REPORT_RPT_NO.nextval
	INTO :new.RPT_NO
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_TBL_RESERVATION_reservNo BEFORE INSERT ON TBL_RESERVATION
FOR EACH ROW
BEGIN
	SELECT SEQ_TBL_RESERVATION_reservNo.nextval
	INTO :new.reservNo
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_TBL_RESERVATION_RESERV_NO BEFORE INSERT ON TBL_RESERVATION
FOR EACH ROW
BEGIN
	SELECT SEQ_TBL_RESERVATION_RESERV_NO.nextval
	INTO :new.RESERV_NO
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_TBL_REVIEW_REPLY_REPORT_rptNo BEFORE INSERT ON TBL_REVIEW_REPLY_REPORT
FOR EACH ROW
BEGIN
	SELECT SEQ_TBL_REVIEW_REPLY_REPORT_rptNo.nextval
	INTO :new.rptNo
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_TBL_REVIEW_REPLY_rvRno BEFORE INSERT ON TBL_REVIEW_REPLY
FOR EACH ROW
BEGIN
	SELECT SEQ_TBL_REVIEW_REPLY_rvRno.nextval
	INTO :new.rvRno
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_TBL_REVIEW_REPLY_RV_RNO BEFORE INSERT ON TBL_REVIEW_REPLY
FOR EACH ROW
BEGIN
	SELECT SEQ_TBL_REVIEW_REPLY_RV_RNO.nextval
	INTO :new.RV_RNO
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_TBL_REVIEW_REPORT_rptNo BEFORE INSERT ON TBL_REVIEW_REPORT
FOR EACH ROW
BEGIN
	SELECT SEQ_TBL_REVIEW_REPORT_rptNo.nextval
	INTO :new.rptNo
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_TBL_REVIEW_rvNo BEFORE INSERT ON TBL_REVIEW
FOR EACH ROW
BEGIN
	SELECT SEQ_TBL_REVIEW_rvNo.nextval
	INTO :new.rvNo
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_TBL_REVIEW_RV_NO BEFORE INSERT ON TBL_REVIEW
FOR EACH ROW
BEGIN
	SELECT SEQ_TBL_REVIEW_RV_NO.nextval
	INTO :new.RV_NO
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_TBL_TIMEFEED_fdNo BEFORE INSERT ON TBL_TIMEFEED
FOR EACH ROW
BEGIN
	SELECT SEQ_TBL_TIMEFEED_fdNo.nextval
	INTO :new.fdNo
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_TBL_TIMEFEED_FD_NO BEFORE INSERT ON TBL_TIMEFEED
FOR EACH ROW
BEGIN
	SELECT SEQ_TBL_TIMEFEED_FD_NO.nextval
	INTO :new.FD_NO
	FROM dual;
END;

/




/* Comments */

COMMENT ON TABLE TBL_BUSIN IS '점포 테이블';
COMMENT ON COLUMN TBL_BUSIN.userId IS '아이디';
COMMENT ON COLUMN TBL_BUSIN.businNo IS '점포번호 : SEQ_BUSIN를 이용';
COMMENT ON COLUMN TBL_BUSIN.lisenceNo IS '사업자등록번호';
COMMENT ON COLUMN TBL_BUSIN.businNm IS '점포명';
COMMENT ON COLUMN TBL_BUSIN.businAddr IS '점포주소1';
COMMENT ON COLUMN TBL_BUSIN.businAddr2 IS '점포주소2';
COMMENT ON COLUMN TBL_BUSIN.businAddr3 IS '점포주소3';
COMMENT ON COLUMN TBL_BUSIN.businTel IS '점포 전화번호';
COMMENT ON COLUMN TBL_BUSIN.businClosedDay IS '휴무일';
COMMENT ON COLUMN TBL_BUSIN.businFood IS '요리종목';
COMMENT ON COLUMN TBL_BUSIN.businScale IS '수용가능인원수';
COMMENT ON COLUMN TBL_BUSIN.businOpen IS '영업시간1';
COMMENT ON COLUMN TBL_BUSIN.businClosed IS '영업시간2';
COMMENT ON COLUMN TBL_BUSIN.businPark IS '주차장유무';
COMMENT ON COLUMN TBL_BUSIN.businBusPhoto IS '사업자등록증사진';
COMMENT ON COLUMN TBL_BUSIN.businPhoto IS '대표사진';
COMMENT ON COLUMN TBL_BUSIN.businEtc IS '기타사항';
COMMENT ON TABLE TBL_BUSIN_ATTACH IS '점포 첨부파일 테이블';
COMMENT ON COLUMN TBL_BUSIN_ATTACH.uuId IS '식별자';
COMMENT ON COLUMN TBL_BUSIN_ATTACH.businNo IS '점포번호 : SEQ_BUSIN를 이용';
COMMENT ON COLUMN TBL_BUSIN_ATTACH.fileName IS '파일명';
COMMENT ON COLUMN TBL_BUSIN_ATTACH.businPath IS '파일경로';
COMMENT ON COLUMN TBL_BUSIN_ATTACH.fileType IS '파일타입';
COMMENT ON TABLE TBL_BUSIN_FAVORITE IS '점포 즐겨찾기 테이블';
COMMENT ON COLUMN TBL_BUSIN_FAVORITE.userId IS '아이디';
COMMENT ON COLUMN TBL_BUSIN_FAVORITE.businNo IS '점포번호 : SEQ_BUSIN를 이용';
COMMENT ON TABLE TBL_BUSIN_REPORT IS '점포 신고 테이블';
COMMENT ON COLUMN TBL_BUSIN_REPORT.reportNo IS '신고번호';
COMMENT ON COLUMN TBL_BUSIN_REPORT.businNo IS '점포번호 : SEQ_BUSIN를 이용';
COMMENT ON COLUMN TBL_BUSIN_REPORT.reporter IS '신고자';
COMMENT ON COLUMN TBL_BUSIN_REPORT.reportCon IS '신고내용';
COMMENT ON COLUMN TBL_BUSIN_REPORT.reportDate IS '신고일시';
COMMENT ON COLUMN TBL_BUSIN_REPORT.processReport IS '신고처리';
COMMENT ON COLUMN TBL_BUSIN_REPORT.restrictionContent IS '제재내용';
COMMENT ON COLUMN TBL_BUSIN_REPORT.restrictionReason IS '제재사유';
COMMENT ON COLUMN TBL_BUSIN_REPORT.restrictionDate IS '제재일시';
COMMENT ON TABLE TBL_COUPON IS '쿠폰 테이블';
COMMENT ON COLUMN TBL_COUPON.couponNo IS '쿠폰번호 : SEQ_COUPON를 이용';
COMMENT ON COLUMN TBL_COUPON.businNo IS '점포번호 : SEQ_BUSIN를 이용';
COMMENT ON COLUMN TBL_COUPON.couponName IS '쿠폰제목';
COMMENT ON COLUMN TBL_COUPON.couponContent IS '쿠폰 내용';
COMMENT ON TABLE TBL_FEED_REPORT IS '피드 신고';
COMMENT ON COLUMN TBL_FEED_REPORT.rptNo IS '신고 번호';
COMMENT ON COLUMN TBL_FEED_REPORT.fdNo IS '피드 번호';
COMMENT ON COLUMN TBL_FEED_REPORT.reporter IS '신고자';
COMMENT ON COLUMN TBL_FEED_REPORT.rptDate IS '신고일시';
COMMENT ON COLUMN TBL_FEED_REPORT.rptContent IS '신고 내용';
COMMENT ON COLUMN TBL_FEED_REPORT.processReport IS '신고처리';
COMMENT ON COLUMN TBL_FEED_REPORT.restrictionContent IS '제재내용';
COMMENT ON COLUMN TBL_FEED_REPORT.restrictionReason IS '제재사유';
COMMENT ON COLUMN TBL_FEED_REPORT.restrictionDate IS '제재일시';
COMMENT ON TABLE TBL_FEED_RP_REPORT IS '피드 댓글 신고';
COMMENT ON COLUMN TBL_FEED_RP_REPORT.rptNo IS '신고 번호';
COMMENT ON COLUMN TBL_FEED_RP_REPORT.fdRpNo IS '피드 댓글 번호';
COMMENT ON COLUMN TBL_FEED_RP_REPORT.reporter IS '신고자';
COMMENT ON COLUMN TBL_FEED_RP_REPORT.rptContent IS '신고 내용';
COMMENT ON COLUMN TBL_FEED_RP_REPORT.rptDate IS '신고일시';
COMMENT ON COLUMN TBL_FEED_RP_REPORT.processReport IS '신고처리';
COMMENT ON COLUMN TBL_FEED_RP_REPORT.restrictionContent IS '제재내용';
COMMENT ON COLUMN TBL_FEED_RP_REPORT.restrictionReason IS '제재사유';
COMMENT ON COLUMN TBL_FEED_RP_REPORT.restrictionDate IS '제재일시';
COMMENT ON TABLE TBL_FOLLOWER IS '팔로워 목록';
COMMENT ON COLUMN TBL_FOLLOWER.userId IS '아이디';
COMMENT ON COLUMN TBL_FOLLOWER.followerUser IS '팔로워 닉네임';
COMMENT ON TABLE TBL_FOLLOWING IS '팔로잉 목록';
COMMENT ON COLUMN TBL_FOLLOWING.userId IS '아이디';
COMMENT ON COLUMN TBL_FOLLOWING.followingUser IS '팔로잉 닉네임';
COMMENT ON TABLE TBL_FREE IS '자유게시판 테이블';
COMMENT ON COLUMN TBL_FREE.freeBno IS '게시판번호 : SEQ_FREE이용';
COMMENT ON COLUMN TBL_FREE.writer IS '작성자';
COMMENT ON COLUMN TBL_FREE.title IS '제목';
COMMENT ON COLUMN TBL_FREE.content IS '내용';
COMMENT ON COLUMN TBL_FREE.regDate IS '작성일자';
COMMENT ON COLUMN TBL_FREE.updateDate IS '수정일자 : 

';
COMMENT ON COLUMN TBL_FREE.replyCnt IS '댓글 수';
COMMENT ON TABLE TBL_FREE_REPLY_REPORT IS '게시글 댓글 신고 테이블';
COMMENT ON COLUMN TBL_FREE_REPLY_REPORT.rptNo IS '신고 번호 : SEQ_FREE_REPLY_RPT를 이용';
COMMENT ON COLUMN TBL_FREE_REPLY_REPORT.freeRno IS '댓글 번호 : SEQ_REPLY를 이용';
COMMENT ON COLUMN TBL_FREE_REPLY_REPORT.reporter IS '신고자';
COMMENT ON COLUMN TBL_FREE_REPLY_REPORT.rptDate IS '신고일시';
COMMENT ON COLUMN TBL_FREE_REPLY_REPORT.rptContent IS '신고 내용';
COMMENT ON COLUMN TBL_FREE_REPLY_REPORT.restrictionContent IS '제재내용';
COMMENT ON COLUMN TBL_FREE_REPLY_REPORT.restrictionReason IS '제재사유';
COMMENT ON COLUMN TBL_FREE_REPLY_REPORT.restrictionDate IS '제재일시';
COMMENT ON TABLE TBL_FREE_REPORT IS '게시글 신고 테이블';
COMMENT ON COLUMN TBL_FREE_REPORT.rptNo IS '신고 번호 : SEQ_REVIEW_REPLY_RPT를 이용';
COMMENT ON COLUMN TBL_FREE_REPORT.freeBno IS '게시판번호 : SEQ_FREE이용';
COMMENT ON COLUMN TBL_FREE_REPORT.reporter IS '신고자';
COMMENT ON COLUMN TBL_FREE_REPORT.rptDate IS '신고일시';
COMMENT ON COLUMN TBL_FREE_REPORT.rptContent IS '신고 내용';
COMMENT ON COLUMN TBL_FREE_REPORT.processReport IS '신고처리';
COMMENT ON COLUMN TBL_FREE_REPORT.restrictionContent IS '제재내용';
COMMENT ON COLUMN TBL_FREE_REPORT.restrictionReason IS '제재사유';
COMMENT ON COLUMN TBL_FREE_REPORT.restrictionDate IS '제재일시';
COMMENT ON TABLE TBL_GON IS '공지사항 테이블';
COMMENT ON COLUMN TBL_GON.gonNo IS '공지게시판 번호 : SEQ_GON이용';
COMMENT ON COLUMN TBL_GON.gonName IS '공지 제목';
COMMENT ON COLUMN TBL_GON.gonContent IS '공지 내용';
COMMENT ON COLUMN TBL_GON.gonRegdate IS '공지 작성일자';
COMMENT ON COLUMN TBL_GON.gonUpdatedate IS '공지 수정일자';
COMMENT ON TABLE TBL_GON_ATTACH IS '공지 첨부파일 테이블';
COMMENT ON COLUMN TBL_GON_ATTACH.gonUuid IS '식별자';
COMMENT ON COLUMN TBL_GON_ATTACH.gonNo IS '공지게시판 번호 : SEQ_GON이용';
COMMENT ON COLUMN TBL_GON_ATTACH.gonFilename IS '파일이름';
COMMENT ON COLUMN TBL_GON_ATTACH.gonUploadPath IS '경로';
COMMENT ON COLUMN TBL_GON_ATTACH.gonFileType IS '파일타입';
COMMENT ON TABLE TBL_MENU IS '메뉴 테이블';
COMMENT ON COLUMN TBL_MENU.menuNo IS '메뉴번호 : SEQ_MENU를 이용';
COMMENT ON COLUMN TBL_MENU.businNo IS '점포번호 : SEQ_BUSIN를 이용';
COMMENT ON COLUMN TBL_MENU.menuNm IS '메뉴이름';
COMMENT ON COLUMN TBL_MENU.menuPrice IS '메뉴가격';
COMMENT ON TABLE TBL_MENU_ATTACH IS '메뉴 파일 테이블';
COMMENT ON COLUMN TBL_MENU_ATTACH.uuid IS '식별자';
COMMENT ON COLUMN TBL_MENU_ATTACH.menuNo IS '메뉴번호 : SEQ_MENU를 이용';
COMMENT ON COLUMN TBL_MENU_ATTACH.fileName IS '파일명';
COMMENT ON COLUMN TBL_MENU_ATTACH.menuPath IS '파일경로';
COMMENT ON TABLE TBL_MSG IS '쪽지함 테이블';
COMMENT ON COLUMN TBL_MSG.msgNo IS '쪽지 번호 : SEQ_MSG이용';
COMMENT ON COLUMN TBL_MSG.msgSender IS '쪽지작성자';
COMMENT ON COLUMN TBL_MSG.msgRecever IS '쪽지수신자';
COMMENT ON COLUMN TBL_MSG.msgContent IS '쪽지 내용';
COMMENT ON COLUMN TBL_MSG.msgRegdate IS '작성일자';
COMMENT ON COLUMN TBL_MSG.msgCheck IS '읽음표시';
COMMENT ON TABLE TBL_MSG_ATTACH IS '쪽지 첨부파일 테이블';
COMMENT ON COLUMN TBL_MSG_ATTACH.gonUuid IS '식별자';
COMMENT ON COLUMN TBL_MSG_ATTACH.msgNo IS '쪽지 번호 : SEQ_MSG이용';
COMMENT ON COLUMN TBL_MSG_ATTACH.gonUploadPath IS '경로';
COMMENT ON COLUMN TBL_MSG_ATTACH.gonFilename IS '파일이름';
COMMENT ON COLUMN TBL_MSG_ATTACH.gonFileType IS '파일타입';
COMMENT ON TABLE TBL_REPLY IS '댓글 테이블';
COMMENT ON COLUMN TBL_REPLY.freeRno IS '댓글 번호 : SEQ_REPLY를 이용';
COMMENT ON COLUMN TBL_REPLY.freeBno IS '게시판번호 : SEQ_FREE이용';
COMMENT ON COLUMN TBL_REPLY.rplWriter IS '댓글작성자';
COMMENT ON COLUMN TBL_REPLY.reply IS '댓글 내용';
COMMENT ON COLUMN TBL_REPLY.replyDate IS '작성일자';
COMMENT ON COLUMN TBL_REPLY.updateDate IS '수정일자';
COMMENT ON TABLE TBL_RESERVATION IS '예약 테이블';
COMMENT ON COLUMN TBL_RESERVATION.reservNo IS '예약 번호 : SEQ_RESERV를 이용';
COMMENT ON COLUMN TBL_RESERVATION.businNo IS '점포번호 : SEQ_BUSIN를 이용';
COMMENT ON COLUMN TBL_RESERVATION.reserver IS '예약자';
COMMENT ON COLUMN TBL_RESERVATION.reservDate IS '예약날짜';
COMMENT ON COLUMN TBL_RESERVATION.headCount IS '인원수';
COMMENT ON COLUMN TBL_RESERVATION.request IS '기타사항';
COMMENT ON COLUMN TBL_RESERVATION.totalPrice IS '총 가격';
COMMENT ON COLUMN TBL_RESERVATION.payDate IS '결제일자';
COMMENT ON COLUMN TBL_RESERVATION.orderNum IS '결제 번호';
COMMENT ON TABLE TBL_REVIEW IS '점포리뷰 테이블';
COMMENT ON COLUMN TBL_REVIEW.rvNo IS '리뷰번호 : SEQ_RV_NO를 이용';
COMMENT ON COLUMN TBL_REVIEW.businNo IS '점포번호 : SEQ_BUSIN를 이용';
COMMENT ON COLUMN TBL_REVIEW.rvWriter IS '리뷰작성자';
COMMENT ON COLUMN TBL_REVIEW.rvTitle IS '리뷰제목';
COMMENT ON COLUMN TBL_REVIEW.stars IS '별점';
COMMENT ON COLUMN TBL_REVIEW.rvContent IS '리뷰내용';
COMMENT ON COLUMN TBL_REVIEW.regDate IS '작성일자';
COMMENT ON COLUMN TBL_REVIEW.updateDate IS '수정일자';
COMMENT ON COLUMN TBL_REVIEW.replyCnt IS '댓글 수';
COMMENT ON TABLE TBL_REVIEW_ATTACH IS '리뷰첨부파일 테이블';
COMMENT ON COLUMN TBL_REVIEW_ATTACH.uuId IS '식별자';
COMMENT ON COLUMN TBL_REVIEW_ATTACH.rvNo IS '리뷰번호 : SEQ_RV_NO를 이용';
COMMENT ON COLUMN TBL_REVIEW_ATTACH.rvFilename IS '파일명';
COMMENT ON COLUMN TBL_REVIEW_ATTACH.uploadPath IS '파일위치';
COMMENT ON TABLE TBL_REVIEW_REPLY IS '리뷰댓글 테이블';
COMMENT ON COLUMN TBL_REVIEW_REPLY.rvRno IS '리뷰댓글번호';
COMMENT ON COLUMN TBL_REVIEW_REPLY.rvNo IS '리뷰번호 : SEQ_RV_NO를 이용';
COMMENT ON COLUMN TBL_REVIEW_REPLY.rvRWritwr IS '리뷰댓글작성자';
COMMENT ON COLUMN TBL_REVIEW_REPLY.rvReply IS '리뷰댓글내용';
COMMENT ON COLUMN TBL_REVIEW_REPLY.regDate IS '작성일자';
COMMENT ON COLUMN TBL_REVIEW_REPLY.updateDate IS '수정일자';
COMMENT ON TABLE TBL_REVIEW_REPLY_REPORT IS '리뷰 댓글 신고 테이블';
COMMENT ON COLUMN TBL_REVIEW_REPLY_REPORT.rptNo IS '신고 번호 : SEQ_REVIEW_REPLY_RPT를 이용';
COMMENT ON COLUMN TBL_REVIEW_REPLY_REPORT.rvRno IS '리뷰댓글번호';
COMMENT ON COLUMN TBL_REVIEW_REPLY_REPORT.reporter IS '신고자';
COMMENT ON COLUMN TBL_REVIEW_REPLY_REPORT.rptDate IS '신고일시';
COMMENT ON COLUMN TBL_REVIEW_REPLY_REPORT.rptContent IS '신고 내용';
COMMENT ON COLUMN TBL_REVIEW_REPLY_REPORT.processReport IS '신고처리';
COMMENT ON COLUMN TBL_REVIEW_REPLY_REPORT.restrictionContent IS '제재내용';
COMMENT ON COLUMN TBL_REVIEW_REPLY_REPORT.restrictionReason IS '제재사유';
COMMENT ON COLUMN TBL_REVIEW_REPLY_REPORT.restrictionDate IS '제재일시';
COMMENT ON TABLE TBL_REVIEW_REPORT IS '리뷰 신고 테이블';
COMMENT ON COLUMN TBL_REVIEW_REPORT.rptNo IS '신고 번호 : SEQ_REVIEW_RPT를 이용';
COMMENT ON COLUMN TBL_REVIEW_REPORT.rvNo IS '리뷰번호 : SEQ_RV_NO를 이용';
COMMENT ON COLUMN TBL_REVIEW_REPORT.reporter IS '신고자';
COMMENT ON COLUMN TBL_REVIEW_REPORT.rptDate IS '신고일시';
COMMENT ON COLUMN TBL_REVIEW_REPORT.rptContent IS '신고 내용';
COMMENT ON COLUMN TBL_REVIEW_REPORT.processReport IS '신고처리';
COMMENT ON COLUMN TBL_REVIEW_REPORT.restrictionContent IS '제재내용';
COMMENT ON COLUMN TBL_REVIEW_REPORT.restrictionReason IS '제재사유';
COMMENT ON COLUMN TBL_REVIEW_REPORT.restrictionDate IS '제재일시';
COMMENT ON TABLE TBL_TIMEFEED IS '타임라인 피드';
COMMENT ON COLUMN TBL_TIMEFEED.fdNo IS '피드 번호';
COMMENT ON COLUMN TBL_TIMEFEED.fdContent IS '피드 내용';
COMMENT ON COLUMN TBL_TIMEFEED.writer IS '작성자';
COMMENT ON COLUMN TBL_TIMEFEED.regDate IS '등록일';
COMMENT ON COLUMN TBL_TIMEFEED.updateDate IS '수정일';
COMMENT ON COLUMN TBL_TIMEFEED.likeCount IS '좋아요';
COMMENT ON COLUMN TBL_TIMEFEED.replyCnt IS '댓글 수';
COMMENT ON TABLE TBL_TIMEFEED_ATTACH IS '피드 첨부파일';
COMMENT ON COLUMN TBL_TIMEFEED_ATTACH.fdNo IS '피드 번호';
COMMENT ON COLUMN TBL_TIMEFEED_ATTACH.uuid IS '식별자';
COMMENT ON COLUMN TBL_TIMEFEED_ATTACH.uploadPath IS '파일 경로';
COMMENT ON COLUMN TBL_TIMEFEED_ATTACH.fileName IS '파일명';
COMMENT ON COLUMN TBL_TIMEFEED_ATTACH.fileType IS '파일 유형';
COMMENT ON TABLE TBL_TIMEFEED_REPLY IS '타임라인 피드 댓글';
COMMENT ON COLUMN TBL_TIMEFEED_REPLY.fdRpNo IS '피드 댓글 번호';
COMMENT ON COLUMN TBL_TIMEFEED_REPLY.fdNo IS '피드 번호';
COMMENT ON COLUMN TBL_TIMEFEED_REPLY.rplWriter IS '댓글작성자';
COMMENT ON COLUMN TBL_TIMEFEED_REPLY.fdRpContent IS '댓글 내용';
COMMENT ON COLUMN TBL_TIMEFEED_REPLY.regDate IS '등록일';
COMMENT ON COLUMN TBL_TIMEFEED_REPLY.updateDate IS '수정일';
COMMENT ON TABLE TBL_USERS IS '회원 테이블';
COMMENT ON COLUMN TBL_USERS.userId IS '아이디';
COMMENT ON COLUMN TBL_USERS.userNm IS '이름';
COMMENT ON COLUMN TBL_USERS.userPw IS '비밀번호';
COMMENT ON COLUMN TBL_USERS.nick IS '닉네임';
COMMENT ON COLUMN TBL_USERS.birthDate IS '생년월일';
COMMENT ON COLUMN TBL_USERS.sex IS '성별';
COMMENT ON COLUMN TBL_USERS.email IS '이메일';
COMMENT ON COLUMN TBL_USERS.phoneNo IS '전화번호';
COMMENT ON COLUMN TBL_USERS.addr1 IS '주소1';
COMMENT ON COLUMN TBL_USERS.addr2 IS '주소2';
COMMENT ON COLUMN TBL_USERS.addr3 IS '주소3';
COMMENT ON COLUMN TBL_USERS.regDate IS '등록일';
COMMENT ON COLUMN TBL_USERS.grade IS '회원등급';
COMMENT ON COLUMN TBL_USERS.userPoint IS '포인트';
COMMENT ON COLUMN TBL_USERS.auth IS '권한';
COMMENT ON COLUMN TBL_USERS.fvrFood IS '선호요리';
COMMENT ON COLUMN TBL_USERS.fvrRes IS '선호가게';
COMMENT ON COLUMN TBL_USERS.pfContent IS '자기소개';
COMMENT ON TABLE TBL_USER_ATTACH IS '회원 첨부파일 테이블';
COMMENT ON COLUMN TBL_USER_ATTACH.uuId IS '식별자';
COMMENT ON COLUMN TBL_USER_ATTACH.userId IS '아이디';
COMMENT ON COLUMN TBL_USER_ATTACH.fileName IS '파일명';
COMMENT ON COLUMN TBL_USER_ATTACH.uploadPath IS '파일위치';
COMMENT ON TABLE TBL_USER_AUTH IS '유저인증테이블';
COMMENT ON COLUMN TBL_USER_AUTH.userid IS '유저id';
COMMENT ON COLUMN TBL_USER_AUTH.auth IS '권한';



